In [1]:
from __future__ import division, print_function, unicode_literals
import numpy as np
import os

def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)
    
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

In [2]:
import tensorflow as tf

/usr/lib64/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
reset_graph()

In [4]:
x = tf.Variable(3, name='x')
y = tf.Variable(4, name='y')

In [5]:
f = x*x*y + y + 2

In [6]:
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()

In [7]:
print(result)

42


In [8]:
f

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [9]:
sess.close()

In [10]:
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)

42


In [11]:
sess.close()

In [12]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    init.run()
    result = f.eval()

In [13]:
result

42

In [14]:
init = tf.global_variables_initializer()

In [15]:
sess = tf.InteractiveSession()

In [16]:
init.run()

In [17]:
result = f.eval()

In [18]:
result

42

In [19]:
sess.close()

In [20]:
result

42

In [21]:
reset_graph()

In [22]:
import numpy as np
from sklearn.datasets import fetch_california_housing

In [23]:
reset_graph()

In [24]:
housing = fetch_california_housing()

In [25]:
m, n = housing.data.shape

In [26]:
m, n

(20640, 8)

In [27]:
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

In [31]:
np.ones((m, 1)).shape

(20640, 1)

In [28]:
housing_data_plus_bias.shape

(20640, 9)

In [29]:
housing_data_plus_bias

array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

In [32]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")

In [35]:
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")

In [36]:
XT = tf.transpose(X)

In [37]:
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

In [41]:
with tf.Session() as sess:
    print(X.eval())
    print("================")
    print(y.eval())
    print("================")
    print(XT.eval())
    theta_value = theta.eval()

[[   1.           8.3252      41.        ...    2.5555556   37.88
  -122.23     ]
 [   1.           8.3014      21.        ...    2.1098418   37.86
  -122.22     ]
 [   1.           7.2574      52.        ...    2.80226     37.85
  -122.24     ]
 ...
 [   1.           1.7         17.        ...    2.3256352   39.43
  -121.22     ]
 [   1.           1.8672      18.        ...    2.1232092   39.43
  -121.32     ]
 [   1.           2.3886      16.        ...    2.616981    39.37
  -121.24     ]]
[[4.526]
 [3.585]
 [3.521]
 ...
 [0.923]
 [0.847]
 [0.894]]
[[   1.           1.           1.        ...    1.           1.
     1.       ]
 [   8.3252       8.3014       7.2574    ...    1.7          1.8672
     2.3886   ]
 [  41.          21.          52.        ...   17.          18.
    16.       ]
 ...
 [   2.5555556    2.1098418    2.80226   ...    2.3256352    2.1232092
     2.616981 ]
 [  37.88        37.86        37.85      ...   39.43        39.43
    39.37     ]
 [-122.23      -122.22  

In [39]:
theta_value

array([[-3.7185181e+01],
       [ 4.3633747e-01],
       [ 9.3952334e-03],
       [-1.0711310e-01],
       [ 6.4479220e-01],
       [-4.0338000e-06],
       [-3.7813708e-03],
       [-4.2348403e-01],
       [-4.3721911e-01]], dtype=float32)

In [42]:
reset_graph()

In [45]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_housing_data = scaler.fit_transform(housing.data)
scaled_housing_data_plus_bias = np.c_[np.ones((m, 1)), scaled_housing_data]

In [56]:
n_epochs = 1000
learning_rate = 0.01

In [57]:
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")

In [58]:
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")

In [59]:
y_pred = tf.matmul(X, theta, name="predictions")

In [60]:
error = y_pred - y

In [61]:
mse = tf.reduce_mean(tf.square(error), name="mse")

In [62]:
gradients = 2/m * tf.matmul(tf.transpose(X), error)

In [63]:
training_op = tf.assign(theta, theta - learning_rate * gradients)

In [64]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    
    best_theta = theta.eval()

Epoch 0 MSE = 9.161542
Epoch 100 MSE = 0.7145004
Epoch 200 MSE = 0.56670487
Epoch 300 MSE = 0.5555718
Epoch 400 MSE = 0.5488112
Epoch 500 MSE = 0.5436363
Epoch 600 MSE = 0.5396291
Epoch 700 MSE = 0.5365092
Epoch 800 MSE = 0.53406775
Epoch 900 MSE = 0.5321473


In [65]:
best_theta

array([[ 2.0685523 ],
       [ 0.8874027 ],
       [ 0.14401656],
       [-0.34770882],
       [ 0.36178368],
       [ 0.00393811],
       [-0.04269556],
       [-0.6614529 ],
       [-0.6375279 ]], dtype=float32)

In [66]:
gradients = tf.gradients(mse, [theta])[0]

In [67]:
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    
    best_theta = theta.eval()

print("Best theta:")
print(best_theta)

Epoch 0 MSE = 9.161542
Epoch 100 MSE = 0.71450037
Epoch 200 MSE = 0.56670487
Epoch 300 MSE = 0.5555718
Epoch 400 MSE = 0.54881126
Epoch 500 MSE = 0.5436363
Epoch 600 MSE = 0.53962916
Epoch 700 MSE = 0.5365092
Epoch 800 MSE = 0.53406775
Epoch 900 MSE = 0.5321473
Best theta:
[[ 2.0685523 ]
 [ 0.8874027 ]
 [ 0.14401656]
 [-0.3477088 ]
 [ 0.36178365]
 [ 0.00393811]
 [-0.04269556]
 [-0.66145283]
 [-0.6375278 ]]


In [68]:
reset_graph()

n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")

In [69]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

In [72]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    print(X.eval())
    print("===========================")
    print(y.eval())

    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    
    best_theta = theta.eval()

print("Best theta:")
print(best_theta)

[[ 1.          2.3447657   0.9821427  ... -0.04959654  1.0525483
  -1.3278352 ]
 [ 1.          2.332238   -0.6070189  ... -0.09251223  1.0431845
  -1.3228439 ]
 [ 1.          1.7826993   1.8561815  ... -0.02584253  1.0385027
  -1.3328265 ]
 ...
 [ 1.         -1.1425933  -0.92485124 ... -0.0717345   1.7782375
  -0.8237132 ]
 [ 1.         -1.054583   -0.8453931  ... -0.09122515  1.7782375
  -0.8736263 ]
 [ 1.         -0.7801295  -1.0043093  ... -0.04368215  1.7501463
  -0.8336958 ]]
[[4.526]
 [3.585]
 [3.521]
 ...
 [0.923]
 [0.847]
 [0.894]]
Epoch 0 MSE = 9.161542
Epoch 100 MSE = 0.7145004
Epoch 200 MSE = 0.56670487
Epoch 300 MSE = 0.5555718
Epoch 400 MSE = 0.54881126
Epoch 500 MSE = 0.5436363
Epoch 600 MSE = 0.53962916
Epoch 700 MSE = 0.5365092
Epoch 800 MSE = 0.53406775
Epoch 900 MSE = 0.5321473
Best theta:
[[ 2.0685523 ]
 [ 0.8874027 ]
 [ 0.14401656]
 [-0.3477088 ]
 [ 0.36178365]
 [ 0.00393811]
 [-0.04269556]
 [-0.66145283]
 [-0.6375278 ]]


In [107]:
import tensorflow as tf

In [108]:
reset_graph()

In [109]:
n_inputs = 28*28
n_hidden1 = 150
n_hidden2 = 150
n_hidden3 = 150
n_hidden4 = 150
n_outputs = 10

In [110]:
X = tf.placeholder(tf.float32, shape=(None, n_inputs), name='X')

In [111]:
y = tf.placeholder(tf.int32, shape=(None), name='y')

In [112]:
def neuron_layer(X, n_neurons, name, activation=None):
    with tf.name_scope(name):
        n_inputs = int(X.get_shape()[1])
        stddev = 2 / np.sqrt(n_inputs)
        init = tf.truncated_normal((n_inputs, n_neurons), stddev=stddev)
        W = tf.Variable(init, name="kernel")
        b = tf.Variable(tf.zeros([n_neurons]), name="bias")
        Z = tf.matmul(X, W) + b
        if activation is not None:
            return activation(Z)
        else:
            return Z

In [113]:
with tf.name_scope("dnn"):
    hidden1 = neuron_layer(X, n_hidden1, name="hidden1",
                           activation=tf.nn.relu)
    hidden2 = neuron_layer(hidden1, n_hidden2, name="hidden2",
                           activation=tf.nn.relu)
    hidden3 = neuron_layer(hidden2, n_hidden3, name="hidden3",
                           activation=tf.nn.relu)
    hidden4 = neuron_layer(hidden3, n_hidden4, name="hidden4",
                           activation=tf.nn.relu)
    logits = neuron_layer(hidden4, n_outputs, name="outputs")

In [114]:
with tf.name_scope("loss"):
    xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,
                                                              logits=logits)
    loss = tf.reduce_mean(xentropy, name="loss")

In [115]:
learning_rate = 0.01

with tf.name_scope("train"):
    optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    training_op = optimizer.minimize(loss)

In [116]:
with tf.name_scope("eval"):
    correct = tf.nn.in_top_k(logits, y, 1)
    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

In [117]:
init = tf.global_variables_initializer()

In [118]:
def shuffle_batch(X, y, batch_size):
    rnd_idx = np.random.permutation(len(X))
    n_batches = len(X) // batch_size
    for batch_idx in np.array_split(rnd_idx, n_batches):
        X_batch, y_batch = X[batch_idx], y[batch_idx]
        yield X_batch, y_batch

In [119]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

In [120]:
X_train = X_train.astype(np.float32).reshape(-1, 28*28) / 255.0
X_test = X_test.astype(np.float32).reshape(-1, 28*28) / 255.0

In [121]:
y_train = y_train.astype(np.int32)
y_test = y_test.astype(np.int32)
X_valid, X_train = X_train[:5000], X_train[5000:]
y_valid, y_train = y_train[:5000], y_train[5000:]

In [122]:
n_epochs = 40
batch_size = 50

In [123]:
with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for X_batch, y_batch in shuffle_batch(X_train, y_train, batch_size):
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        acc_batch = accuracy.eval(feed_dict={X: X_batch, y: y_batch})
        acc_val = accuracy.eval(feed_dict={X: X_valid, y: y_valid})
        print(epoch, "Batch accuracy:", acc_batch, "Val accuracy:", acc_val)

0 Batch accuracy: 0.94 Val accuracy: 0.9298
1 Batch accuracy: 0.94 Val accuracy: 0.9442
2 Batch accuracy: 0.96 Val accuracy: 0.9518
3 Batch accuracy: 0.96 Val accuracy: 0.9586
4 Batch accuracy: 0.98 Val accuracy: 0.9662
5 Batch accuracy: 0.96 Val accuracy: 0.9616
6 Batch accuracy: 1.0 Val accuracy: 0.9666
7 Batch accuracy: 1.0 Val accuracy: 0.9692
8 Batch accuracy: 1.0 Val accuracy: 0.9726
9 Batch accuracy: 0.98 Val accuracy: 0.9724
10 Batch accuracy: 1.0 Val accuracy: 0.9712
11 Batch accuracy: 1.0 Val accuracy: 0.975
12 Batch accuracy: 0.98 Val accuracy: 0.9704
13 Batch accuracy: 1.0 Val accuracy: 0.972
14 Batch accuracy: 1.0 Val accuracy: 0.9762
15 Batch accuracy: 0.98 Val accuracy: 0.9748
16 Batch accuracy: 1.0 Val accuracy: 0.9746
17 Batch accuracy: 1.0 Val accuracy: 0.9772
18 Batch accuracy: 1.0 Val accuracy: 0.976
19 Batch accuracy: 1.0 Val accuracy: 0.9766
20 Batch accuracy: 1.0 Val accuracy: 0.9766
21 Batch accuracy: 1.0 Val accuracy: 0.9758
22 Batch accuracy: 1.0 Val accuracy: